name: Default Browser with Puppeteer 

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create headless browser script
        run: |
          sudo tee ${GITHUB_WORKSPACE}/webBrowserHeadless > /dev/null << 'EOF'
          #!/usr/bin/env node
          console.log("Starting webBrowserHeadless");
          const url = process.argv[2];
          console.log('Got URL ${url}');
          EOF
  
          sudo chmod +x webBrowserHeadless
          ln -s ${GITHUB_WORKSPACE}/webBrowserHeadless /usr/local/bin/webBrowserHeadless
          
      - name: Verify webBrowserHeadless script works as expected
        run: |
          ls -l /usr/local/bin/webBrowserHeadless
          if webBrowserHeadless https://example.com | grep -q "<title>Example Domain</title>" ; then
            echo "✅ webBrowserHeadless executed successfully"
          else
            echo "❌ webBrowserHeadless failed"
            exit 1
          fi
          
      - name: Setup default browser
        run: |
          sudo update-alternatives --install /usr/bin/www-browser www-browser /usr/local/bin/webBrowserHeadless 100
          sudo update-alternatives --set www-browser /usr/local/bin/webBrowserHeadless
          ls -l /etc/alternatives | grep browser

      - name: Test opening some URL with default browser (xdg-open)
        run: |
          if xdg-open https://example.com | grep -q "<title>Example Domain</title>" ; then
            echo "✅ xdg-open executed successfully"
          else
            echo "❌ xdg-open failed"
            exit 1
          fi
    
