# This is a basic workflow to help you get started with Actions
  
name: PharoJsTestFirefox

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Start virtual framebuffer XVFB
        env:
          DISPLAY: ":99"
        run: |
          sudo apt-get install -y xvfb
          Xvfb :99 -screen 0 1920x1080x24 &

      # From https://github.com/browser-actions
      - name: Setup Firefox
        uses: browser-actions/setup-firefox@v1
          
      - name: Create headless browser script
        run: |
          sudo tee /usr/local/bin/webBrowserHeadless > /dev/null << 'EOF'
          #!/bin/sh
          firefox --headless\
            --disable-gpu\
          "${@}" 2>/dev/null
          EOF
  
          sudo chmod +x /usr/local/bin/webBrowserHeadless
              
      - name: Setup default browser
        run: |
          sudo update-alternatives --install /usr/bin/www-browser www-browser /usr/local/bin/webBrowserHeadless 100
          sudo update-alternatives --set www-browser /usr/local/bin/webBrowserHeadless
          ls -l /etc/alternatives | grep browser
      - name: Test opening some URL with webBrowserHeadless
        uses: coactions/setup-xvfb@v1.0.1 # From https://github.com/marketplace/actions/setup-xvfb
        with:
          run: |
            if webBrowserHeadless https://example.com ; then
              echo "✅ webBrowserHeadless executed successfully"
            else
              echo "❌ webBrowserHeadless failed"
              exit 1
            fi  
      # From https://github.com/actions/setup-node
      - uses: actions/setup-node@v4
        # with:
        #   node-version: 20
          # cache: 'npm'
          # cache-dependency-path: '**/package-lock.json'

      # From https://github.com/actions/checkout
      - uses: actions/checkout@v4
        with: 
          # Recommended by SmalltalkCi action
          # Iceberg requires full history
          fetch-depth: 0 # Option fetching all commits

      # From https://github.com/marketplace/actions/setup-smalltalkci
      - uses: hpi-swa/setup-smalltalkCI@v1
        id: smalltalkci
        with:
          smalltalk-image: 'Pharo64-12'

      - name: run tests
        run: smalltalkci -s ${{ steps.smalltalkci.outputs.smalltalk-image }}
        shell: bash
        timeout-minutes: 15
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # uses: coactions/setup-xvfb@v1.0.1 # From https://github.com/marketplace/actions/setup-xvfb
        # env:
        #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # with:
        #   run: smalltalkci -s ${{ steps.smalltalkci.outputs.smalltalk-image }}
        #   shell: bash
        #   timeout-minutes: 15

