# This is a basic workflow to help you get started with Actions
  
name: Headless Script Default Browser

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
      # From https://github.com/browser-actions
      # - name: Setup Firefox
      #   uses: browser-actions/setup-firefox@v1
      # - name: Setup Chrome
      #   uses: browser-actions/setup-chrome@v1
      - name: Install Chrome
        run: |
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable curl
          
      - name: Create headless browser script
        run: |
          sudo tee /usr/local/bin/webBroswerHeadless > /dev/null << 'EOF'
          #!/bin/sh
          google-chrome --headless=new \
          --disable-gpu \
          --no-sandbox \
          --disable-dev-shm-usage \
          --dump-dom "${@}" 2>/dev/null
          EOF
  
          sudo chmod +x /usr/local/bin/webBroswerHeadless
          
      - name: Verify script creation
        run: |
          ls -l /usr/local/bin/webBroswerHeadless
          cat /usr/local/bin/webBroswerHeadless
          /usr/local/bin/webBroswerHeadless https://example.com
          
      - name: Setup default browser
        run: |
          sudo update-alternatives --install /usr/bin/www-browser www-browser /usr/local/bin/webBroswerHeadless 100
          sudo update-alternatives --set www-browser /usr/local/bin/webBroswerHeadless
          ls -l /etc/alternatives | grep browser

      - name: Test openning some URL
        run: |
          if xdg-open https://example.com; then
            echo "✅ xdg-open executed successfully"
          else
            echo "❌ xdg-open failed"
            exit 1
          fi
    
